{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ $.Values.revision }}
    path: {{ .path }}
    helm:
      values:
        {{ .values | toYaml | indent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .destinationNamespace }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
{{- end }}
