{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  project: {{ $.Values.project }}
  source:
    chart: {{ .chartName }}
    repoURL: {{ .repoURL }}
    targetRevision: {{ .revision }}
    path: {{ .path }}
    helm:
      valuesObject:
        {{- toYaml .values | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .destinationNamespace }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
{{- end }}
