{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .revision }}
    path: {{ .path }}
    helm:
      values: |
        {{- toYaml .values | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .destinationNamespace }}
  {{- with .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Prune=true
      - RespectIgnoreDifferences=true
{{- end }}
