apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql-db.fullname" . }}
  labels:
    {{- include "mssql-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ range .Values.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{ end }}
  selector:
    {{- include "mssql-db.selectorLabels" . | nindent 4 }}
