# Default values for btds-tekton-pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

git:
  url: "git@git.bcbssc.com:InformationSystems/ocp_btds_debezium.git"
  revision: "feature/test"
  githubwebookenabled: false
  webhookSecret: "change-me" # Secret token for GitHub webhook validation

workspace:
  size: 5Gi
  # Use allowed storage class for commercial tenant

maven:
  image: "images.pkgrepo.bcbssc.com/maven:3.9-eclipse-temurin-21"
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "2"
      memory: "4Gi"
