namespace: openshift-gitops
project: default

applications: []
  # - name: kafka
  #   repoURL: https://github.com/ryan-highley/amq-streams-debezium-workshop.git
  #   revision: main
  #   path: helm/
  #   chartName: kafka
  #   destinationNamespace: kafka
  #   values: {}

  # - name: kafkaconnect
  #   repoURL: https://github.com/ryan-highley/amq-streams-debezium-workshop.git
  #   revision: main
  #   path: helm/
  #   chartName: kafkaconnect
  #   destinationNamespace: kafkaconnect
  #   values: {}

  # - name: tekton-pipeline
  #   repoURL: https://github.com/ryan-highley/amq-streams-debezium-workshop.git
  #   revision: main
  #   path: helm/
  #   chartName: tekton-pipeline
  #   destinationNamespace: tekton-pipeline
  #   values: {}
