namespace: openshift-gitops
project: default

repoURL: https://github.com/ryan-highley/amq-streams-debezium-workshop.git
revision: main

applications:
  - name: kafka
    path: helm/kafka
    destinationNamespace: kafka
    values: {}

  # - name: kafkaconnect
  #   path: helm/kafkaconnect
  #   destinationNamespace: kafkaconnect
  #   values: {}

  - name: tekton-pipeline
    path: helm/tekton-pipeline
    destinationNamespace: tekton-pipeline
    values: {}
