---
# ------------------------------------------------
# Tenant ArgoCD App Workload
# ------------------------------------------------

# Required definitions:
#   ocp4_workload_tenant_argocd_app_gitops_repo_url
#   ocp4_workload_tenant_argocd_app_name

ocp4_workload_tenant_argocd_app_gitops_repo_revision: "main"
ocp4_workload_tenant_argocd_app_gitops_repo_path: ""

ocp4_workload_tenant_argocd_app_namespace: "{{ ocp4_workload_tenant_openshift_gitops_namespace | default('openshift-gitops') }}"

ocp4_workload_tenant_argocd_appproject_name: "{{ ocp4_workload_tenant_openshift_gitops_user_project_prefix | default('default') }}"
