---
# ------------------------------------------------
# Tenant ArgoCD App Workload
# ------------------------------------------------

# Required definitions:
#   ocp4_workload_tenant_argocd_app_gitops_repo_url
#   ocp4_workload_tenant_argocd_app_name

ocp4_workload_tenant_argocd_app_gitops_repo_revision: "main"
ocp4_workload_tenant_argocd_app_gitops_repo_path: ""

ocp4_workload_tenant_argocd_app_namespace: openshift-gitops

ocp4_workload_tenant_argocd_app_project_name: default

ocp4_workload_tenant_argocd_app_user_project_prefix: appproject
