{{- range .Values.kafkaTopics }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ $.Values.kafka.localcluster.clustername }}
  name: {{ .name }}
  namespace: {{ $.Values.kafka.localcluster.namespace}}
  # annotations:
  #  helm.sh/hook: post-install,post-upgrade
  #  helm.sh/hook-weight: "3"
spec:
  config:
    cleanup.policy: compact
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: {{.partitions}}
  replicas: {{ $.Values.kafka.localcluster.replicas }}
{{- end }}
