{{- if .Values.git.githubwebookenabled -}}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: debezium-webhook
  namespace: {{ .Values.global.namespace }}
spec:
  serviceAccountName: debezium-webhook-sa
  triggers:
    - name: github-push-events
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: token
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref == 'refs/heads/{{ .Values.git.revision }}'"
      bindings:
        - ref: github-trigger-binding
      template:
        ref: github-trigger-template
{{- end -}}
