{{- if .Values.git.githubwebookenabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  token: {{ .Values.git.webhookSecret | quote }}
{{- end -}}
