apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ toYaml .Values.selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.selectorLabels | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mssql
          image: {{ .Values.image }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dataMount }}
          volumeMounts:
            - name: {{ .name }}
              mountPath: {{ .path }}
          {{- end }}
      {{- with .Values.dataMount }}
      volumes:
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
      {{- end }}
