apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
spec:
  hostname: {{ .Values.hostname }}
{{- with .Values.kafkaClusters }}
  kafkaClusters:
    {{ toYaml . | nindent 4 }}
{{- end }}
