apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
spec:
  hostname: {{ .Values.hostname }}
  security:
    {{- with .Values.oidc }}
    oidc:
      {{ toYaml . | nindent 6 }}
      trustStore:
        type: PEM
        content:
          valueFrom:
            secretKeyRef:
              name: keycloak-tls-secret
              key: ca.crt
    {{- end }}
    subjects:
      - include:
          - admin
        roleNames:
          - administrators
      - include:
          - developer
        roleNames:
          - developers
    roles:
      - name: developers
        rules:
          - resources:
              - kafkas
            resourceNames:
              - '*'
            privileges:
              - 'ALL'
      - name: administrators
        rules:
          - resources:
              - kafkas
            resourceNames:
              - '*'
            privileges:
              - 'ALL'
{{- with .Values.kafkaClusters }}
  kafkaClusters:
    {{ toYaml . | nindent 4 }}
{{- end }}
