
namespaces:
  dev: dev
  db: db
  showroom: showroom
  kafka: tenant-comm-kafka
  debezium: tenant-comm-debezium

consoleLinks:
  - name: showroom
    spec:
      href: https://www.example.com
      location: NamespaceDashboard
      text: Custom Link Text
      namespaceDashboard:
        namespaces:
        - default
